### ISSUE TITLE
Tuyển dụng flutter

### ISSUE THREAD

**Issue by phudqph09495** [locnd95/MovieApp#1]
Chào bạn mình là Duyên HCNS công ty SOTA mình thấy bạn đang muốn ứng tuyển vào vị trí lập trình viên Flutter bên công ty mình trên TopCV bạn có thể liên hệ với mình qua số điện thoại 0865208100 hoặc để lại số điện thoại để bên mình có thể liên hệ với bạn. 

Rất mong nhận được sự phản hồi của bạn

**Comment by locnd95** [comment]
0346418055 sdtt của mình đây nhé .Bạn kb vs mình qua zalo nch cũng đc

Vào 11:44, T.6, 26 Th5, 2023 phudqph0311 ***@***.***> đã viết:
